{{- $manageConfig := and .Values.config.manage (not .Values.config.existingSecret) -}}
{{- $manageDbPassword := not .Values.database.existingSecret -}}
{{- if or $manageConfig $manageDbPassword }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "baikal.fullname" . }}
  labels:
    {{- include "baikal.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if $manageConfig }}
  baikal.yaml: |
    {{- include "baikal.configFile" . | nindent 4 }}
  encryption-key: {{ include "baikal.encryptionKey" . | quote }}
  {{- end }}
  {{- if $manageDbPassword }}
  mysql-password: {{ .Values.database.password | quote }}
  {{- end }}
{{- end }}
